version: '2.1'

services:
  blogged:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../:/usr/app
    ports:
      - '8000:8000'
    entrypoint:
      - /usr/app/docker/dev/entrypoint.sh
